export const homeImage = require("../../assets/images/homeimg.png")
export const logo = require("../../assets/images/logo.png")
export const greenHairMan = require("../../assets/images/signimg.png")
export const googleIcon = require("../../assets/images/google.png")
export const appleIcon = require("../../assets/images/apple.png")
export const githubIcon = require("../../assets/images/github.png")